add form to submit new trips
MiejkeHoltermann/capstone-project pull request #8
Opened 2023-08-14 15:11 UTC by MiejkeHoltermann

2023-08-14 22:58 UTC, NicoleHoerner requested changes
Very nice!😃
Just the console.log. (but I am not that experienced in reviewing code)

2023-08-14 22:58 UTC, NicoleHoerner commented on pages/index.js
> +    console.log(trips);
I think we should not have any console.logs in our final code.

2023-08-15 09:56 UTC, F-Kirchhoff requested changes
This looks already great. I added some suggestions how you can structure your code a bit better. Have a look!

2023-08-15 09:56 UTC, F-Kirchhoff commented on public/trips.js
>    },
please don't put this file into the public folder. This should only contain elements that are shipped directly to the client. You can create a db folder and put this file in there.

2023-08-15 09:56 UTC, F-Kirchhoff commented on pages/index.js
> +    const formattedEndDate = `${endDay}/${endMonth}/${endYear}`;
you can write a little helper function called 'parseDate' to use it for the start and end date. By this, you don't multiply your code.

2023-08-15 09:56 UTC, F-Kirchhoff commented on pages/index.js
> +    console.log(formattedStartDate, formattedEndDate);
please remove all logs before starting the PR 🕵️

2023-08-15 10:18 UTC, F-Kirchhoff approved these changes
LGTM, please move the helper function formatDate in a separate file as described. but you can go to the QA afterwards

2023-08-15 10:18 UTC, F-Kirchhoff commented on pages/index.js
> +  }
please move this function into a folder called `lib/utils.js` and import it here again (only for best practice reasons). You don't need to repost the PR though.

2023-08-15 10:18 UTC, F-Kirchhoff commented on pages/index.js
> +    console.log(updatedTrips);
🕵️

2023-08-15 10:50 UTC, F-Kirchhoff approved these changes
LGTM

2023-08-15 10:50 UTC, F-Kirchhoff commented on components/TripInputForm.js
> +        min={start}
sweet!

2023-08-15 12:05 UTC, merged